version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myappdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/myappdb
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db-data:
